### ISSUE TITLE
MongoDB support-logging retrieving token from Valut failed

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/blackbox-testing#398] opened 2020-02-25 10:18 UTC
run nightly-build [docker-compose-nexus-mongo.yml](https://github.com/edgexfoundry/developer-scripts/blob/master/releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml)

support-logging log:
```
level=WARN ts=2020-02-25T09:52:19.7861621Z app=edgex-support-logging source=config.go:82 msg="could not get configuration from Registry: the Configuration service (Consul) doesn't contain configuration for edgex/core/1.0/edgex-support-logging/"
level=WARN ts=2020-02-25T09:52:20.7966604Z app=edgex-support-logging source=config.go:82 msg="could not get configuration from Registry: the Configuration service (Consul) doesn't contain configuration for edgex/core/1.0/edgex-support-logging/"
level=INFO ts=2020-02-25T09:52:21.8107448Z app=edgex-support-logging source=bootstrap.go:133 msg="Loaded configuration from http://edgex-core-consul:8500"
level=INFO ts=2020-02-25T09:52:21.8138003Z app=edgex-support-logging source=registry.go:49 msg="Using Registry from http://edgex-core-consul:8500"
level=INFO ts=2020-02-25T09:52:21.8242153Z app=edgex-support-logging source=config.go:138 msg="Writeable configuration has been updated from the Configuration Provider"
level=ERROR ts=2020-02-25T09:52:21.9859806Z app=edgex-support-logging source=secret.go:67 msg="unable to create SecretClient: HTTP response with status code 503, message: failed to lookup token"
level=INFO ts=2020-02-25T09:52:21.9906885Z app=edgex-support-logging source=bootstrap.go:160 msg="Un-Registering service from the Registry"
```
should be fixed in [edgexfoundry/go-mod-secrets#49](https://github.com/edgexfoundry/go-mod-secrets/issues/49)

**Comment by cloudxxx8** [comment] 2020-02-25 10:27
The issue is fixed in go-mod-secrets version v0.0.17, waiting for edgex-go to adopt this version

**Comment by bnevis-i** [comment] 2020-02-27 15:25
This issue has been fixed and can be closed.

**Comment by cloudxxx8** [comment] 2020-02-27 15:47
thanks, @bnevis-i

**Closed as completed by cloudxxx8** 2020-02-27 15:47 UTC
