### ISSUE TITLE
Kong docker image is unable to pull at arm64 env

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/blackbox-testing#185] opened 2019-03-21 04:42 UTC
In the recent build job, they both fail at here.
```
10:47:54 Pulling kong-migration (kong:0.13.0)...
10:47:55 no matching manifest for unknown in the manifest list entries
10:47:55 Build step 'Execute shell' marked build as failure
```
Please refer to below links:
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-ubuntu18.04-docker-arm64-4c-2g-master/39/console
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-ubuntu18.04-docker-arm64-4c-2g-master/40/console

It seems didn't support official image for arm64.
https://github.com/Kong/docker-kong/issues/39

Add @tingyuz for awareness.

**Comment by anonymouse64** [comment] 2019-03-27 16:15
FWIW for the snap, we build kong and it's dependencies from the source on arm64 using ubuntu and it works fine. See the code to build it all here: https://github.com/edgexfoundry/edgex-go/blob/40a2af237db18e5bdb72a1e5e3b53b3733364037/snap/snapcraft.yaml#L640-L781

**Comment by hutchic** [comment] 2019-04-15 14:36
@anonymouse64 if I'm not mistaken that builds an arm32 snap which will work on arm64 but FWIW I don't believe Kong will work when compiled against arm64 until OpenResty [1.15.8.1](https://openresty.org/en/ann-1015008001rc1.html)

**Comment by anonymouse64** [comment] 2019-04-15 14:54
@hutchic No that runs on a native arm64 machine and as such builds an arm64 snap. I haven't ever tried to build the snap on a native arm32 (also called armhf in snap terminology) system.

**Comment by anonymouse64** [comment] 2019-04-15 14:58
@hutchic BTW if you want to take a look, I also made a snap of just Kong with these parts here: https://github.com/anonymouse64/kong-snap

I set that snap up to build with build.snapcraft.io and it apparently builds fine on an armhf system as well (see example launchpad build here: https://launchpad.net/~build.snapcraft.io/+snap/d2ca0034ce2748c30b0a921e5ed19d8c/+build/439471) but I admit I never actually tested that kong snap on an armhf system

**Comment by hutchic** [comment] 2019-04-16 11:26
@anonymouse64 while that looks to build a snap successfully I can't seem to run anything via said snap

```
sudo snap install kong
kong migrations up
kong migrations list
kong start
```

Which matches my expectation of installing / configuring Kong on an arm64 ec2 as follows: https://gist.github.com/hutchic/d833c0ea85b867e74a7c2a2a6e898707

**Comment by anonymouse64** [comment] 2019-04-16 12:29
@hutchic which architecture is that on?

**Comment by hutchic** [comment] 2019-04-16 17:02
```
ubuntu@ip-172-31-27-205:~$ uname -m
aarch64
ubuntu@ip-172-31-27-205:~$ uname -a
Linux ip-172-31-27-205 4.15.0-1028-aws #29~16.04.1+nutmeg8-Ubuntu SMP Tue Nov 20 03:44:55 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by tingyuz** [comment] 2019-04-16 17:56
@hutchic I recalled you mentioned this is working on  arm64 ec2 https://github.com/svenwal/kong-arm. 
can you confirm/verify if it is working with arm32?

**Comment by hutchic** [comment] 2019-04-16 18:54
@tingyuz that does work on arm32 and arm64 it's via `FROM arm32v6/alpine:3.6`

https://github.com/svenwal/kong-arm/blob/master/Dockerfile#L1
https://github.com/hypriot/rpi-alpine/blob/master/Dockerfile#L1

**Comment by anonymouse64** [comment] 2019-04-19 03:05
@hutchic so my arm64 machine was down for a while but after getting it back online, I know run into this problem when attempting to use kong on arm64 (compiled using the snap):

<details>
  <summary>Click to expand</summary>

```
ubuntu@localhost:~$ sudo kong migrations up --yes --conf /var/snap/kong/current/config/kong.conf --vv
2019/04/19 03:02:38 [verbose] Kong: 0.13.1
2019/04/19 03:02:38 [debug] ngx_lua: 10010
2019/04/19 03:02:38 [debug] nginx: 1011002
2019/04/19 03:02:38 [debug] Lua: LuaJIT 2.1.0-beta3
2019/04/19 03:02:38 [verbose] reading config file at /var/snap/kong/current/config/kong.conf
2019/04/19 03:02:38 [warn] You are using Cassandra but your 'db_update_propagation' setting is set to '0' (default). Due to the distributed nature of Cassandra, you should increase this value.
2019/04/19 03:02:38 [debug] admin_access_log = "logs/admin_access.log"
2019/04/19 03:02:38 [debug] admin_error_log = "logs/error.log"
2019/04/19 03:02:38 [debug] admin_listen = {"127.0.0.1:8001","127.0.0.1:8444 ssl"}
2019/04/19 03:02:38 [debug] anonymous_reports = true
2019/04/19 03:02:38 [debug] cassandra_consistency = "ONE"
2019/04/19 03:02:38 [debug] cassandra_contact_points = {"127.0.0.1"}
2019/04/19 03:02:38 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2019/04/19 03:02:38 [debug] cassandra_keyspace = "kong"
2019/04/19 03:02:38 [debug] cassandra_lb_policy = "RoundRobin"
2019/04/19 03:02:38 [debug] cassandra_port = 9042
2019/04/19 03:02:38 [debug] cassandra_repl_factor = 1
2019/04/19 03:02:38 [debug] cassandra_repl_strategy = "SimpleStrategy"
2019/04/19 03:02:38 [debug] cassandra_schema_consensus_timeout = 10000
2019/04/19 03:02:38 [debug] cassandra_ssl = false
2019/04/19 03:02:38 [debug] cassandra_ssl_verify = false
2019/04/19 03:02:38 [debug] cassandra_timeout = 5000
2019/04/19 03:02:38 [debug] cassandra_username = "kong"
2019/04/19 03:02:38 [debug] client_body_buffer_size = "8k"
2019/04/19 03:02:38 [debug] client_max_body_size = "0"
2019/04/19 03:02:38 [debug] client_ssl = false
2019/04/19 03:02:38 [debug] custom_plugins = {}
2019/04/19 03:02:38 [debug] database = "cassandra"
2019/04/19 03:02:38 [debug] db_cache_ttl = 3600
2019/04/19 03:02:38 [debug] db_update_frequency = 5
2019/04/19 03:02:38 [debug] db_update_propagation = 0
2019/04/19 03:02:38 [debug] dns_error_ttl = 1
2019/04/19 03:02:38 [debug] dns_hostsfile = "/etc/hosts"
2019/04/19 03:02:38 [debug] dns_no_sync = false
2019/04/19 03:02:38 [debug] dns_not_found_ttl = 30
2019/04/19 03:02:38 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2019/04/19 03:02:38 [debug] dns_resolver = {}
2019/04/19 03:02:38 [debug] dns_stale_ttl = 4
2019/04/19 03:02:38 [debug] error_default_type = "text/plain"
2019/04/19 03:02:38 [debug] latency_tokens = true
2019/04/19 03:02:38 [debug] log_level = "notice"
2019/04/19 03:02:38 [debug] lua_package_cpath = ""
2019/04/19 03:02:38 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2019/04/19 03:02:38 [debug] lua_socket_pool_size = 30
2019/04/19 03:02:38 [debug] lua_ssl_verify_depth = 1
2019/04/19 03:02:38 [debug] mem_cache_size = "128m"
2019/04/19 03:02:38 [debug] nginx_daemon = "on"
2019/04/19 03:02:38 [debug] nginx_optimizations = true
2019/04/19 03:02:38 [debug] nginx_user = "root root"
2019/04/19 03:02:38 [debug] nginx_worker_processes = "auto"
2019/04/19 03:02:38 [debug] pg_database = "kong"
2019/04/19 03:02:38 [debug] pg_host = "127.0.0.1"
2019/04/19 03:02:38 [debug] pg_port = 5432
2019/04/19 03:02:38 [debug] pg_ssl = false
2019/04/19 03:02:38 [debug] pg_ssl_verify = false
2019/04/19 03:02:38 [debug] pg_user = "kong"
2019/04/19 03:02:38 [debug] prefix = "/var/snap/kong/74"
2019/04/19 03:02:38 [debug] proxy_access_log = "logs/access.log"
2019/04/19 03:02:38 [debug] proxy_error_log = "logs/error.log"
2019/04/19 03:02:38 [debug] proxy_listen = {"0.0.0.0:8000","0.0.0.0:8443 ssl"}
2019/04/19 03:02:38 [debug] real_ip_header = "X-Real-IP"
2019/04/19 03:02:38 [debug] real_ip_recursive = "off"
2019/04/19 03:02:38 [debug] server_tokens = true
2019/04/19 03:02:38 [debug] ssl_cipher_suite = "modern"
2019/04/19 03:02:38 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2019/04/19 03:02:38 [debug] trusted_ips = {}
2019/04/19 03:02:38 [debug] upstream_keepalive = 60
2019/04/19 03:02:38 [verbose] prefix in use: /var/snap/kong/74
2019/04/19 03:02:39 [verbose] running datastore migrations
Error: 
/snap/kong/74/share/lua/5.1/kong/cmd/migrations.lua:34: [cassandra error] could not find coordinator: all hosts tried for query failed. 127.0.0.1: host seems unhealthy, considering it down (connection refused)
stack traceback:
	[C]: in function 'assert'
	/snap/kong/74/share/lua/5.1/kong/cmd/migrations.lua:34: in function 'cmd_exec'
	/snap/kong/74/share/lua/5.1/kong/cmd/init.lua:87: in function </snap/kong/74/share/lua/5.1/kong/cmd/init.lua:87>
	[C]: in function 'xpcall'
	/snap/kong/74/share/lua/5.1/kong/cmd/init.lua:87: in function </snap/kong/74/share/lua/5.1/kong/cmd/init.lua:44>
	/snap/kong/74/bin/kong:7: in function 'file_gen'
	init_worker_by_lua:49: in function <init_worker_by_lua:47>
	[C]: in function 'xpcall'
	init_worker_by_lua:56: in function <init_worker_by_lua:54>

```
</details>

Is this the expected issue when running natively on arm64 (and not using a multiarch solution like the above dockerfile)?

**Comment by hutchic** [comment] 2019-04-19 14:03
That is not expected. It looks like an issue with Kong connecting to cassandra / cassandra not being fully provisioned and available yet ( https://github.com/Kong/kong/issues/2949 )

**Comment by anonymouse64** [comment] 2019-04-19 17:41
@hutchic okay that's what I thought too, can you provide an example of what the output should look like on arm64 when compiled natively for arm64? To me, it seems that while Kong wasn't able to migrate to cassandra, it is still run successfully (which matches my original check I did on arm64 a few months ago when first adding support for kong to the snap) 

I'm just trying to reproduce the issue you described above with:

> I don't believe Kong will work when compiled against arm64 until OpenResty 1.15.8.1

**Comment by hutchic** [comment] 2019-04-20 13:28
>  can you provide an example of what the output should look like on arm64 when compiled natively for arm64

Since I've never got this to work (compiled on arm64 running on arm64) or found an example of this working no I cannot. I can provide an example of what 86_64 looks like or arm32v6

**Comment by anonymouse64** [comment] 2019-04-30 19:27
After setting up a 2 GB swapfile so I can actually get cassandra to run on a raspberry pi 3b+ running ubuntu server 18.04.2 arm64, I see the following behavior:

```
ubuntu@ubuntu:~$ sudo kong migrations up --vv --yes --conf /var/snap/kong/current/config/kong.conf
2019/04/30 19:16:55 [verbose] Kong: 0.13.1
2019/04/30 19:16:55 [debug] ngx_lua: 10010
2019/04/30 19:16:55 [debug] nginx: 1011002
2019/04/30 19:16:55 [debug] Lua: LuaJIT 2.1.0-beta3
2019/04/30 19:16:55 [verbose] reading config file at /var/snap/kong/current/config/kong.conf
2019/04/30 19:16:55 [warn] You are using Cassandra but your 'db_update_propagation' setting is set to '0' (default). Due to the distributed nature of Cassandra, you should increase this value.
2019/04/30 19:16:55 [debug] admin_access_log = "logs/admin_access.log"
2019/04/30 19:16:55 [debug] admin_error_log = "logs/error.log"
2019/04/30 19:16:55 [debug] admin_listen = {"127.0.0.1:8001","127.0.0.1:8444 ssl"}
2019/04/30 19:16:55 [debug] anonymous_reports = true
2019/04/30 19:16:55 [debug] cassandra_consistency = "ONE"
2019/04/30 19:16:55 [debug] cassandra_contact_points = {"127.0.0.1"}
2019/04/30 19:16:55 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2019/04/30 19:16:55 [debug] cassandra_keyspace = "kong"
2019/04/30 19:16:55 [debug] cassandra_lb_policy = "RoundRobin"
2019/04/30 19:16:55 [debug] cassandra_port = 9042
2019/04/30 19:16:55 [debug] cassandra_repl_factor = 1
2019/04/30 19:16:55 [debug] cassandra_repl_strategy = "SimpleStrategy"
2019/04/30 19:16:55 [debug] cassandra_schema_consensus_timeout = 10000
2019/04/30 19:16:55 [debug] cassandra_ssl = false
2019/04/30 19:16:55 [debug] cassandra_ssl_verify = false
2019/04/30 19:16:55 [debug] cassandra_timeout = 5000
2019/04/30 19:16:55 [debug] cassandra_username = "kong"
2019/04/30 19:16:55 [debug] client_body_buffer_size = "8k"
2019/04/30 19:16:55 [debug] client_max_body_size = "0"
2019/04/30 19:16:55 [debug] client_ssl = false
2019/04/30 19:16:55 [debug] custom_plugins = {}
2019/04/30 19:16:55 [debug] database = "cassandra"
2019/04/30 19:16:55 [debug] db_cache_ttl = 3600
2019/04/30 19:16:55 [debug] db_update_frequency = 5
2019/04/30 19:16:55 [debug] db_update_propagation = 0
2019/04/30 19:16:55 [debug] dns_error_ttl = 1
2019/04/30 19:16:55 [debug] dns_hostsfile = "/etc/hosts"
2019/04/30 19:16:55 [debug] dns_no_sync = false
2019/04/30 19:16:55 [debug] dns_not_found_ttl = 30
2019/04/30 19:16:55 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2019/04/30 19:16:55 [debug] dns_resolver = {}
2019/04/30 19:16:55 [debug] dns_stale_ttl = 4
2019/04/30 19:16:55 [debug] error_default_type = "text/plain"
2019/04/30 19:16:55 [debug] latency_tokens = true
2019/04/30 19:16:55 [debug] log_level = "notice"
2019/04/30 19:16:55 [debug] lua_package_cpath = ""
2019/04/30 19:16:55 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2019/04/30 19:16:55 [debug] lua_socket_pool_size = 30
2019/04/30 19:16:55 [debug] lua_ssl_verify_depth = 1
2019/04/30 19:16:55 [debug] mem_cache_size = "128m"
2019/04/30 19:16:55 [debug] nginx_daemon = "on"
2019/04/30 19:16:55 [debug] nginx_optimizations = true
2019/04/30 19:16:55 [debug] nginx_user = "root root"
2019/04/30 19:16:55 [debug] nginx_worker_processes = "auto"
2019/04/30 19:16:55 [debug] pg_database = "kong"
2019/04/30 19:16:55 [debug] pg_host = "127.0.0.1"
2019/04/30 19:16:55 [debug] pg_port = 5432
2019/04/30 19:16:55 [debug] pg_ssl = false
2019/04/30 19:16:55 [debug] pg_ssl_verify = false
2019/04/30 19:16:55 [debug] pg_user = "kong"
2019/04/30 19:16:55 [debug] prefix = "/var/snap/kong/74"
2019/04/30 19:16:55 [debug] proxy_access_log = "logs/access.log"
2019/04/30 19:16:55 [debug] proxy_error_log = "logs/error.log"
2019/04/30 19:16:55 [debug] proxy_listen = {"0.0.0.0:8000","0.0.0.0:8443 ssl"}
2019/04/30 19:16:55 [debug] real_ip_header = "X-Real-IP"
2019/04/30 19:16:55 [debug] real_ip_recursive = "off"
2019/04/30 19:16:55 [debug] server_tokens = true
2019/04/30 19:16:55 [debug] ssl_cipher_suite = "modern"
2019/04/30 19:16:55 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2019/04/30 19:16:55 [debug] trusted_ips = {}
2019/04/30 19:16:55 [debug] upstream_keepalive = 60
2019/04/30 19:16:55 [verbose] prefix in use: /var/snap/kong/74
Error: 
bad light userdata pointer
stack traceback:
	[C]: at 0xffffa9bf8670
	[C]: in function 'require'
	/snap/kong/74/share/lua/5.1/kong/dao/db/cassandra.lua:6: in main chunk
	[C]: in function 'require'
	/snap/kong/74/share/lua/5.1/kong/dao/factory.lua:102: in function 'new'
	/snap/kong/74/share/lua/5.1/kong/cmd/migrations.lua:31: in function 'cmd_exec'
	/snap/kong/74/share/lua/5.1/kong/cmd/init.lua:87: in function </snap/kong/74/share/lua/5.1/kong/cmd/init.lua:87>
	[C]: in function 'xpcall'
	/snap/kong/74/share/lua/5.1/kong/cmd/init.lua:87: in function </snap/kong/74/share/lua/5.1/kong/cmd/init.lua:44>
	/snap/kong/74/bin/kong:7: in function 'file_gen'
	init_worker_by_lua:49: in function <init_worker_by_lua:47>
	[C]: in function 'xpcall'
	init_worker_by_lua:56: in function <init_worker_by_lua:54>
```

@hutchic is that what you would expect to see on arm64 natively without openresty 1.15?
If so then the next question would be can we use openresty 1.15 with kong 1.0.3 so that arm64 works natively?

**Comment by hutchic** [comment] 2019-05-01 04:16
The PR to upgrade openresty to 1.15.8.1 is here https://github.com/Kong/kong/pull/4382 I suspect we won't merge it until that version of openresty is out of RC at minimum. So at this time I do not believe it's possible for Kong to operate on arm64 natively

**Comment by cloudxxx8** [comment] 2019-05-19 09:04
@weichou1229 nexus3.edgexfoundry.org:10004/kong-arm is ready, please help update the script to use this image for ARM test

**Comment by cloudxxx8** [comment] 2019-05-20 06:32
fixed by #230

**Comment by cloudxxx8** [comment] 2019-05-23 15:22
The image can't run normally.  Please see
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-ubuntu18.04-docker-arm64-4c-2g-master/117/consoleFull

> [1BStarting edgex-vault ... 
> 20:32:31 [1A[2K
> Starting edgex-vault ... [32mdone[0m
> [1B[1A[2K
> Starting kong-migration ... [32mdone[0m
> [1BStarting kong ... 
> 20:32:33 Starting kong
> 20:32:35 [1A[2K
> Starting kong ... [32mdone[0m
> [1Bstandard_init_linux.go:190: exec user process caused "exec format error"
> 20:32:38 Build step 'Execute shell' marked build as failure
> 20:32:38 $ ssh-agent -k

**Comment by anonymouse64** [comment] 2019-05-23 18:58
@cloudxxx8 that's the issue I was describing in the devops WG call I was mentioning. The `exec format error` comes from the fact that we are trying to run an armhf 32-bit binary on an arm64 QEMU virtual CPU, and QEMU arm64 doesn't support running armhf the same way that a real arm64 machine does.

I'm not sure we can realistically test Kong + security-api-gateway on arm64 until either:
* Kong supports running on arm64 natively which it sounds like won't happen until openresty 1.15 is released and the Kong is updated to support this
* We have the ability to run tests on native arm64 hardware
* We have some way to run Kong for testing on an armhf virtual host, with the rest of EdgeX running on an arm64 virtual host

@hutchic any thoughts on how soon we might see a native arm64 version of Kong released? I see there has been another RC of openresty but the associated PRs you mention haven't had any activity on them in the past 2 weeks.

**Comment by hutchic** [comment] 2019-05-23 20:12
~The key component might be that the Kong container needs to be built natively on arm not via qemu (waiting on sven to confirm)~ this turned out to not be the case sven's image is build on x86 w\ qemu so it's curious that sven's docker image worked but the one picked up by blackbox-testing didn't

`svenwal/kong-arm` works on x86_64 via qemu emulation
```
uname -m
x86_64
docker run --rm --privileged multiarch/qemu-user-static:register --reset
docker run -it --rm svenwal/kong-arm kong version
1.0.3
docker run -it --rm svenwal/kong-arm uname -m
armv7l
```

`svenwal/kong-arm` works natively on a aws arm instance
```
uname -m
aarch64
docker run -it --rm svenwal/kong-arm kong version
1.0.3
docker run -it --rm svenwal/kong-arm uname -m
aarch64
```

I'm not confident on a timeline but I can say that as of May 17 Openresty 1.15.8.1 is out of RC ( https://openresty.org/en/ann-1015008001.html )

I suspect in preparation for `Openresty 1.15.8.1` we'll have official arm32 builds of Kong available first

**Comment by anonymouse64** [comment] 2019-05-23 22:55
> `svenwal/kong-arm` works on x86_64 via qemu emulation

This is because the emulation is done for an `armhf` processor, not an arm64 process, so running armhf on armhf virtual is fine (otherwise the virtualization would be entirely broken). The case I was referring to is having a virtual `arm64` OS, and running `armhf` binaries inside the arm64 virtual OS. That is what fails in the jenkins build that @cloudxxx8 linked to.

> `svenwal/kong-arm` works natively on a aws arm instance

This is because AFAIK, the arm instances are native arm64, not emulated: https://aws.amazon.com/blogs/aws/new-ec2-instances-a1-powered-by-arm-based-aws-graviton-processors/


> I suspect in preparation for `Openresty 1.15.8.1` we'll have official arm32 builds of Kong available first

I'm not sure how much this will help the QA team for this issue, because currently the only arm machines we can provision for running these tests is a virtual arm64 instance, so even official arm32 support won't help the tests run here.
It's good to hear that OpenResty 1.15 is out of RC though

**Comment by hutchic** [comment] 2019-05-23 23:56
Are you certain the EC2 a1 instances aren't true arm?
>Today we are launching EC2 instances powered by Arm-based AWS Graviton Processors. Built around Arm cores

Also I've ran `svenwal/kong-arm` on a raspberrypi before so that's an added datapoint which I think is helpful

**Comment by anonymouse64** [comment] 2019-06-03 17:28
> Also I've ran `svenwal/kong-arm` on a raspberrypi before so that's an added datapoint which I think is helpful

Right this makes sense and matches my expectation. 

To summarize:

- On QEMU / virtualized arm64 CPUs, 64-bit arm64 compiled kong **_doesn't_** run because OpenResty 1.15 is needed
- On QEMU/virtualized arm64 CPUs, 32-bit armhf compiled kong **_doesn't_** run because QEMU arm64 doesn't support 32-bit armhf binaries
- On native arm64 CPUs, 64-bit arm64 compiled kong **_doesn't_** run because OpenResty 1.15 is needed
- On native arm64 CPUs, 32-bit armhf compiled kong **_does_** run because native arm64 CPUs are backwards compatible with 32-bit armhf binaries
- On native armhf CPUs, 32-bit armhf compiled kong **_does_** work because there's no 64-bit related issues

So the following situations apply:

- EdgeX Foundry's Jenkins servers **_don't_** work because they are virtualized arm64 CPUs
- AWS arm64 EC2 instances **_do_** work with `svenwal/kong-arm` because they are native arm64 processors
- Local Raspberry Pi 3B+ arm64 Ubuntu Server 18.04 images **_do_** work with `svenwal/kong-arm` because they too are native arm64 processors

**Comment by anonymouse64** [comment] 2019-08-22 13:55
Kong 1.3.0 has been released which should support arm64 natively with the new version of OpenResty, so work on this can resume I think

**Comment by hutchic** [comment] 2019-08-22 14:32
In my tests Kong 1.3.0 is arm64 native compatible it was the final thing merged so I still need to adjust some build pipeline stuff to actually build / release said arm artifacts

**Comment by anonymouse64** [comment] 2019-08-22 14:43
For the snap at least, we build kong and OpenResty from source so that shouldn't be an issue for the snap, but for the docker image that sounds like it will be necessary.

**Comment by cloudxxx8** [comment] 2019-08-24 08:59
@cherrycl please try to update the kong image on arm64

**Comment by cherrycl** [comment] 2019-08-26 07:55
I tried to pull kong:1.3.0 on raspberry pi (arm64) from docker hub, got the following error.
The image is still not supported arm64.

> ubuntu@raspi3bplus-arm64:~/edgexfoundry$ docker pull kong:1.3.0
> 1.3.0: Pulling from library/kong
> no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by cloudxxx8** [comment] 2019-08-26 08:00
@jamesrgregg is your team available to provide the help to build the image of Kong1.3.0 on arm64?  Thanks.

**Comment by anonymouse64** [comment] 2019-08-26 11:25
@cloudxxx8 I think your team will need to wait for @hutchic (and their team possibly) to build the arm64 docker images, the new release supports arm64, but they have finished releasing arm64 artifacts AIUI

**Comment by cloudxxx8** [comment] 2019-08-26 12:18
@anonymouse64 thanks for the update.  we will wait for that.

**Comment by jeremyxu2010** [comment] 2019-09-05 13:07
> In my tests Kong 1.3.0 is arm64 native compatible it was the final thing merged so I still need to adjust some build pipeline stuff to actually build / release said arm artifacts

@hutchic Can you push an arm64 kong docker image to the dockerhub's personal subrepository ? This image is urgently needed.

**Comment by hutchic** [comment] 2019-09-05 23:24
Still tracking down some compile / build issues that need to be resolved

Currently able to build a Kong asset for Xenial and Trusty. Bionic and Alpine are both failing currently. If we can't resolve it in the near future I can push an unofficial Kong image

**Comment by jeremyxu2010** [comment] 2019-09-06 08:16
> Still tracking down some compile / build issues that need to be resolved
> 
> Currently able to build a Kong asset for Xenial and Trusty. Bionic and Alpine are both failing currently. If we can't resolve it in the near future I can push an unofficial Kong image

@hutchic  `kong arm64 docker image based Xenial` is just ok. Urgently need this.

**Comment by jeremyxu2010** [comment] 2019-09-06 23:22
> Still tracking down some compile / build issues that need to be resolved
> 
> Currently able to build a Kong asset for Xenial and Trusty. Bionic and Alpine are both failing currently. If we can't resolve it in the near future I can push an unofficial Kong image

@hutchic I resolved compile issues with kong 1.3.0 image for ubuntu Xenial, [Dockerfile](https://gist.github.com/jeremyxu2010/a3fb26b00aaaab52c48139f980ad4a95)

**Comment by jamesrgregg** [comment] 2019-09-23 19:06
@cloudxxx8 I saw your message and it seems you're on the right path after debugging the problem.  @ernestojeda is working on an alpine based base image, which should be smaller than the ubuntu based image that we see referenced in the note from @hutchic

**Comment by hutchic** [comment] 2019-09-24 13:30
We ran into challenges with musl on alpine and compiling lua / openresty. If @ernestojeda has a way to work around those issue I'll gladly incorporate that into the official Kong:alpine image.

The Ubuntu based arm64 image is pending here: https://github.com/docker-library/official-images/pull/6661

**Comment by jeremyxu2010** [comment] 2019-09-25 07:30
@hutchic I have tried to build kong on arm64v8/alpine:3.10. 

If I apply the patch [LuaJIT-2.1-20190507_03-dyn-lightuserdata-map.patch](https://github.com/Kong/openresty-patches/blob/master/patches/1.15.8.1/LuaJIT-2.1-20190507_03-dyn-lightuserdata-map.patch)，then compiled output  "/usr/local/openresty/luajit/bin/luajit" is broken. Executing it will get `Aborted (core dumped)` error. 

If I reverse the patch [LuaJIT-2.1-20190507_03-dyn-lightuserdata-map.patch](https://github.com/Kong/openresty-patches/blob/master/patches/1.15.8.1/LuaJIT-2.1-20190507_03-dyn-lightuserdata-map.patch),  then compiled output  "/usr/local/openresty/luajit/bin/luajit" is ok.  But use this luajit to compile kong will get `bad light userdata pointer` error.

So I thought maybe the patch [LuaJIT-2.1-20190507_03-dyn-lightuserdata-map.patch](https://github.com/Kong/openresty-patches/blob/master/patches/1.15.8.1/LuaJIT-2.1-20190507_03-dyn-lightuserdata-map.patch) should be improved to support musl on alpine.

**Comment by hutchic** [comment] 2019-09-25 16:39
@jeremyxu2010 yes that's correct 👍 

We're aware of the alpine issue but don't have a timeline immediately available. For the time being use the official Kong arm64 ubuntu image (pending the aforementioned approval /  merge) or use an unofficial arm32 image ( https://github.com/svenwal/kong-arm )

**Comment by hutchic** [comment] 2019-10-04 17:46
I believe this can be closed now

**Comment by cloudxxx8** [comment] 2019-10-25 05:45
Kong image on arm64 can run now

**Closed as completed by cloudxxx8** 2019-10-25 05:45 UTC
